name: Random Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # Runs at 05:30 UTC (Modify randomly)
    - cron: '15 14 * * *' # Runs at 14:15 UTC on some days
  workflow_dispatch:  # 👈 Allows manual trigger from GitHub Actions

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Randomness (Skip Some Days)
      run: |
        RANDOM_NUM=$(( RANDOM % 10 ))  # Random number between 0-9
        if [[ $RANDOM_NUM -lt 3 ]]; then
          echo "Skipping commit today to look human."
          exit 0
        fi

    - name: Modify file slightly
      run: |
        FILE="random-commit.txt"
        DATE=$(date "+%Y-%m-%d %H:%M:%S")
        echo "Commit made on $DATE with a small change." >> $FILE
        git add $FILE

    - name: Commit and push changes
      run: |
        COMMIT_MESSAGES=("Updated some minor stuff" "Refactoring in progress" "Small tweak made" "Fixing minor issue" "Just improving things" "Optimizing structure" "Bug fix applied" "Reviewing some logic" "Enhancing performance" "Cleanup done")
        RANDOM_MSG=${COMMIT_MESSAGES[$RANDOM % ${#COMMIT_MESSAGES[@]}]}

        git config --global user.name "Bhagyaban Ghadai"
        git config --global user.email "bhagyaban@users.noreply.github.com"
        git commit -m "$RANDOM_MSG" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
